### ISSUE TITLE
BIL Link

### ISSUE THREAD

**Issue by emseabee** [tbep-tech/equity-plan-mapping#2]
https://github.com/tbep-tech/equity-plan-mapping/blob/ff8938fa37d1bc18f863e34ee857f23ceba9f98c/index.qmd#L20

I updated this link to the actual IIJA text. If you want to direct folks to the EPA BIL Fact sheets (instead of the USDOT broken link), here it is: https://www.epa.gov/infrastructure

**Comment by fawda123** [comment]
Link shouldn't be in quotes, I fixed it.
