### ISSUE TITLE
Clarification of EPA definition for underserved

### ISSUE THREAD

**Issue by fawda123** [tbep-tech/equity-plan-mapping#5]
https://github.com/tbep-tech/equity-plan-mapping/blob/e32a2ff66220e7cc24d9ebc8cde0ebe88f388647/underserved.qmd#L54

This is a little unclear, does EPA use the average percentile across all five, i.e., if the average falls above 80% it's "underserved"?  I think this relates to @emseabee comment on #4

**Comment by BAlexSimmons** [comment]
Clarified
